"""Create table Users

Revision ID: 7586851476b5
Revises: 8dc4f07b252a
Create Date: 2024-05-02 17:26:01.918840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7586851476b5'
down_revision: Union[str, None] = '8dc4f07b252a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(length=128), server_default='', nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('phones', sa.Column('category_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'phones', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'phones', type_='foreignkey')
    op.drop_column('phones', 'category_id')
    op.drop_table('categories')
    # ### end Alembic commands ###
